server:
  port: 8082
  
# default설정
spring:
  profiles:
    active: local
---
spring:
  config:
    active:
      on-profile: local
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2